#https://docs.microsoft.com/en-us/azure/aks/kubernetes-action

name: Build and push the latest build to staging cluster

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
 
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Azure Kubernetes set context
        uses: Azure/aks-set-context@v1.1
        with:
          # Azure credentials i.e. output of `az ad sp create-for-rbac --sdk-auth`
          creds: '${{ secrets.AKS_CREDENTIALS }}'
          # Resource Group Name
          resource-group: test-aks
          # AKS Cluster Name
          cluster-name: test-aks
      - name: Deploy to Kubernetes cluster
        uses: Azure/k8s-deploy@v1.3
        with:
          # Choose the target Kubernetes namespace. If the namespace is not provided, the commands will run in the default namespace.
          # Path to the manifest files which will be used for deployment.
          manifests: deploy.yaml
          # Deploy when a previous deployment already exists. If true then --force argument is added to the apply command
          force: true
          # Github token
          token: ${{ github.token }}
